use HOSPITAL;
CREATE TABLE EXAMINATION(
    ID  INTEGER AUTO_INCREMENT,
    PatientID CHAR(9) NOT NULL,
    NurseID CHAR(9) NOT NULL,
    DocID CHAR(9) NOT NULL,
    ShiftID CHAR(11) NOT NULL,
    DiagRes VARCHAR(256) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(PatientID) REFERENCES PATIENT(ID),
    FOREIGN KEY(NurseID) REFERENCES NURSE(ID),
    FOREIGN KEY(DocID) REFERENCES DOCTOR(ID),
    FOREIGN KEY(ShiftID) REFERENCES SHIFT(ID)
);
