use HOSPITAL;
CREATE TABLE HOSPITAL.PRESCRIPTION(
    ID INTEGER AUTO_INCREMENT,
    ExamID INTEGER NOT NULL, 
    DocID CHAR(9) NOT NULL, 
    Diet VARCHAR(256),
    PRIMARY KEY(Id),
    FOREIGN KEY(DocID) REFERENCES DOCTOR(ID),
    FOREIGN KEY(ExamID) REFERENCES EXAMINATION(ID)
);