use HOSPITAL;
CREATE TABLE SHIFT(
    ID  CHAR(11) NOT NULL,
    DepartID INTEGER NOT NULL,
    Dates Date,
    Periods ENUM('A','B'),
    PRIMARY KEY(ID),
    FOREIGN KEY(DepartID) REFERENCES DEPARTMENT(ID)
);