use HOSPITAL;
 table TAKETEST(
    ExamID INTEGER NOT NULL,
    TestID INTEGER DEFAULT 0,
    FTestID INTEGER DEFAULT 0,
    PRIMARY KEY(TestID, FTestID, ExamID),
    FOREIGN KEY(ExamID) REFERENCES EXAMINATION(ID),
    FOREIGN KEY(TestID) REFERENCES Test(ID),
    FOREIGN KEY(FTestID) REFERENCES Ftest(ID)
);